// Code generated by Kitex v0.6.2. DO NOT EDIT.

package consisservice

import (
	"context"
	consis "github.com/T4t4KAU/TikBase/pkg/rpc/consis"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Join(ctx context.Context, req *consis.JoinReq, callOptions ...callopt.Option) (r *consis.JoinResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConsisServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConsisServiceClient struct {
	*kClient
}

func (p *kConsisServiceClient) Join(ctx context.Context, req *consis.JoinReq, callOptions ...callopt.Option) (r *consis.JoinResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Join(ctx, req)
}
