# 存储引擎配置
store:
  type: "base"
  directory: ""
  indexer: "art"
  datafile_size: 1024
  bytes_per_sync: 1000
  sync_writes: true
  write_batch:
    max_batch_num: 10000
    sync_writes: true
  datafile_merge_ratio: 10
  iterator:
    prefix: ""
    reverse: true
  mmap_at_startup: true

# 网络配置
server:
  tcp_port: 9096
  http_port: 9098
  workers_num: 20
  timeout: 60


