// Code generated by Kitex v0.6.2. DO NOT EDIT.

package metaservice

import (
	"context"
	meta0 "github.com/T4t4KAU/TikBase/pkg/rpc/meta"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegionList(ctx context.Context, req *meta0.RegionListReq, callOptions ...callopt.Option) (r *meta0.RegionListResp, err error)
	RegionStatus(ctx context.Context, req *meta0.RegionStatusReq, callOptions ...callopt.Option) (r *meta0.RegionStatusResp, err error)
	ReplicaList(ctx context.Context, req *meta0.ReplicaListReq, callOptions ...callopt.Option) (r *meta0.ReplicaListResp, err error)
	ReplicaStatus(ctx context.Context, req *meta0.ReplicaStatusReq, callOptions ...callopt.Option) (r *meta0.ReplicaStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMetaServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMetaServiceClient struct {
	*kClient
}

func (p *kMetaServiceClient) RegionList(ctx context.Context, req *meta0.RegionListReq, callOptions ...callopt.Option) (r *meta0.RegionListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegionList(ctx, req)
}

func (p *kMetaServiceClient) RegionStatus(ctx context.Context, req *meta0.RegionStatusReq, callOptions ...callopt.Option) (r *meta0.RegionStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegionStatus(ctx, req)
}

func (p *kMetaServiceClient) ReplicaList(ctx context.Context, req *meta0.ReplicaListReq, callOptions ...callopt.Option) (r *meta0.ReplicaListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReplicaList(ctx, req)
}

func (p *kMetaServiceClient) ReplicaStatus(ctx context.Context, req *meta0.ReplicaStatusReq, callOptions ...callopt.Option) (r *meta0.ReplicaStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReplicaStatus(ctx, req)
}
