// Code generated by Kitex v0.6.2. DO NOT EDIT.

package replicaservice

import (
	"context"
	replica "github.com/T4t4KAU/TikBase/pkg/rpc/replica"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Join(ctx context.Context, req *replica.JoinReq, callOptions ...callopt.Option) (r *replica.JoinResp, err error)
	LeaderAddr(ctx context.Context, req *replica.LeaderAddrReq, callOptions ...callopt.Option) (r *replica.LeaderAddrResp, err error)
	GetId(ctx context.Context, req *replica.GetIdReq, callOptions ...callopt.Option) (r *replica.GetIdResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kReplicaServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kReplicaServiceClient struct {
	*kClient
}

func (p *kReplicaServiceClient) Join(ctx context.Context, req *replica.JoinReq, callOptions ...callopt.Option) (r *replica.JoinResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Join(ctx, req)
}

func (p *kReplicaServiceClient) LeaderAddr(ctx context.Context, req *replica.LeaderAddrReq, callOptions ...callopt.Option) (r *replica.LeaderAddrResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LeaderAddr(ctx, req)
}

func (p *kReplicaServiceClient) GetId(ctx context.Context, req *replica.GetIdReq, callOptions ...callopt.Option) (r *replica.GetIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetId(ctx, req)
}
